//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital
{
    using System;
    using System.Collections.Generic;
    
    public partial class list
    {
        public int id_list { get; set; }
        public Nullable<int> id_doc { get; set; }
        public Nullable<int> id_person { get; set; }
        public string course_name { get; set; }
        public Nullable<System.DateTime> a_date { get; set; }
        public string time { get; set; }
        public string notes { get; set; }
    
        public virtual doc doc { get; set; }
        public virtual person person { get; set; }
    }
}
