//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital
{
    using System;
    using System.Collections.Generic;
    
    public partial class person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public person()
        {
            this.list = new HashSet<list>();
            this.reception = new HashSet<reception>();
        }
    
        public int id_person { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string last_name { get; set; }
        public string adress { get; set; }
        public Nullable<System.DateTime> b_date { get; set; }
        public string p_num { get; set; }
        public string b_type { get; set; }
        public string insurance_c { get; set; }
        public Nullable<long> insurance_num { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<list> list { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reception> reception { get; set; }
    }
}
