//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital
{
    using System;
    using System.Collections.Generic;
    
    public partial class reception
    {
        public int id_rec { get; set; }
        public Nullable<int> id_person { get; set; }
        public Nullable<System.DateTime> r_date { get; set; }
        public Nullable<System.DateTime> l_date { get; set; }
    
        public virtual person person { get; set; }
    }
}
